### PR TITLE
Review

### PR DESCRIPTION
**Pull request by hanmao**
@codepathreview @codepath Please review, Thanks

### CODE REVIEW

**Comment by nesquena** [comment]
Hanxiao,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Since there have been over 60 applications and we can only accept 15 people into the pilot course, the next step is to **work on one or two [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo)**. This course is project-based and the optional extensions on each project are often the most valuable learnings since they dive deeper into common Android use cases.

Once you submit 1-2 extensions, your application will be passed along to the organizers for final enrollment. Let me know if you have any questions in the meantime.

**Comment by hanmao** [comment]
what's the deadline to submit the extension to do task?

Sent from my iPhone

On Nov 15, 2015, at 10:49 AM, Nathan Esquenazi <notifications@github.com<mailto:notifications@github.com>> wrote:

Hanxiao,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Since there have been over 60 applications and we can only accept 15 people into the pilot course, the next step is to work on one or two extensions to your todo apphttp://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo. This course is project-based and the optional extensions on each project are often the most valuable learnings since they dive deeper into common Android use cases.

Once you submit 1-2 extensions, your application will be passed along to the organizers for final enrollment. Let me know if you have any questions in the meantime.

##

**Comment by nesquena** [comment]
We are accepting people on a first come first serve basis once they've submitted 1-2 extensions until all 15 slots are filled up. There are still many slots left.

**Comment by hanmao** [comment]
How many extensions should I add so I can fill up the slots?

Sent from my iPhone

On Nov 15, 2015, at 11:06 AM, Nathan Esquenazi <notifications@github.com<mailto:notifications@github.com>> wrote:

We are accepting people on a first come first serve basis once they've submitted extensions until all 15 slots are filled up. There are still many slots left.

##

**Comment by nesquena** [comment]
I'd suggest SQLite and Custom Todo Item Adapter to be best prepared for the class. Links for how are in the pre-work.

**Comment by hanmao** [comment]
Hi, Nathan:

I added SQLite and Custom Adapter, please help me review it.

https://github.com/hanmao/Android-ToDO/tree/secondCOmmit

Thanks

Hanxiao

**Comment by nesquena** [comment]
Great to see you were able to augment your app with a few extension tasks now including database persistence. As mentioned earlier, the extension tasks available on each project are often the most valuable learnings since they dive deeper into common real-world Android use cases.

Your application will be passed along to the organizers for final admissions. You should hear back again soon. Let me know if you have any questions in the meantime.

**Comment by hanmao** [comment]
could i add more extesion features today?

Sent from my iPhone

On Nov 16, 2015, at 10:44 AM, Nathan Esquenazi <notifications@github.com<mailto:notifications@github.com>> wrote:

Great to see you were able to augment your app with a few extension tasks now including database persistence. As mentioned earlier, the extension tasks available on each project are often the most valuable learnings since they dive deeper into common real-world Android use cases.

Your application will be passed along to the organizers for final admissions. You should hear back again soon. Let me know if you have any questions in the meantime.

##

**Comment by nesquena** [comment]
Of course, please feel free to continue augmenting the todo app.

**Comment by hanmao** [comment]
Thanks, Nathan.

I added two more extension feature:

```
1. Add support for completion due dates for todo items
```
1. Use a DialogFragment instead of new Activity for editing items

Thanks

Hanxiao

**Comment by nesquena** [comment]
Great, thanks for the updates!

**Comment by hanmao** [comment]
Am I able to enrolled in the training?

Sent from my iPhone

On Nov 17, 2015, at 11:50 PM, Nathan Esquenazi <notifications@github.com<mailto:notifications@github.com>> wrote:

Great, thanks for the updates!

##

**Pull request merged**
